### ISSUE TITLE
Cant request anything

### ISSUE THREAD

**Issue by K2ouMais** [netojose/laravel-api-explorer#9] opened 2019-12-10 14:02 UTC
Hi,

I installed your package and it looks really good.

Unfortunately it doesnt work with any of my APIs.

I have set global headers:
Content-Type: application/json
Accept: application/json

![Request_02](https://user-images.githubusercontent.com/52510455/70535688-c6d55680-1b5d-11ea-8099-4f75e3397b02.png)

And here I am trying to send some JSON data:
![Request_01](https://user-images.githubusercontent.com/52510455/70535844-09972e80-1b5e-11ea-9c66-7143f6d3f23d.png)

For some reason nothing works ;o(

I dont get any response or error.

EDIT:

It seems only the first request doesnt work.

Could it be, because there are 4 Fields in the JSON?

Other requests where I send JSON are working flawlessly.

**Comment by netojose** [comment] 2019-12-10 14:58
@K2ouMais , can you paste here the response from the server when this error occurs?

**Comment by K2ouMais** [comment] 2019-12-10 15:37
I can request exactly the same with postman oder over a *.http file on my IDE.

Over you tool, seems that the request doesnt even startet.

You click the button "MAKE REQUEST" and nothing happens.

**Comment by netojose** [comment] 2019-12-10 15:58
@K2ouMais , I can't reproduce your error. You can see on the network tab if the request starts and if it has some response? (network tab from chrome dev tools)

**Comment by K2ouMais** [comment] 2019-12-11 07:04
No the request doesnt start and so it does not have a response. Strange...

For some reason it just happens with this POST request.

All others work without a problem.

**Comment by K2ouMais** [comment] 2019-12-11 07:08
I just found where the problem was.

If you for some reason have a an empty field in the Header Section the request doesnt even start.

![HereIsTheProblem](https://user-images.githubusercontent.com/52510455/70599437-6e4d9a00-1bed-11ea-8761-4fdf8e121078.png)

**Comment by netojose** [comment] 2019-12-11 12:54
@K2ouMais , thanks for your investigation. I will add some input validation on these fields, or ignore empty fields when requesting, on the Front-end side

**Comment by K2ouMais** [comment] 2019-12-11 13:31
Muito obrigado entao ;oD

Thank you for the effort.

**Comment by netojose** [comment] 2019-12-12 11:32
@K2ouMais , bug fixed on 2.0.1 version (already is available). Now, parameters with empty key and/or values, are ignored.

Fix here: https://github.com/netojose/laravel-api-explorer/commit/a4808fcecb15b2de2b1d5eae6051a208e9846eff

Thank you for your cooperation!

**Closed by netojose** 2019-12-12 11:32 UTC

**Comment by K2ouMais** [comment] 2019-12-12 11:41
Just tried ist out and the same problem still occurs.

You have to ignore parameters with empty keys and values on Headers.

**Comment by netojose** [comment] 2019-12-12 11:55
But @K2ouMais , this change updates the function used by format headers and parameters. So, it works.
Please check:

* If you updated to 2.0.1 version
* Cleared your cache (because front end uses a bundle.js file and can be cached)

**Comment by K2ouMais** [comment] 2019-12-12 12:01
I cleared the cache, but for some unknown reason it didnt got clear.

Now I cleared it again and it works the way you wanted.

This is FIXED

Thank you

**Comment by netojose** [comment] 2019-12-12 12:36
I will fix this, appending some querystring variable when calling bundle.js (like bundle.js?v=2.0.2) to avoid these kind of cache issues in the future.
